### ISSUE TITLE
Dozens of AVs detect the wrapper as malware

### ISSUE THREAD

**Issue by jyrkive** [portapps/discord-portable#7]
https://www.virustotal.com/#/file/bb5e59d432cb3d06521c60ec3d877f2841664a39445e735d43859c131b4b5d3f/detection

32 AVs is so many that I'm rather going to believe that the latest version really *is* infected, rather than going to run it on my PC.

**Comment by crazy-max** [comment]
Hi @jyrkive,

It's the same issue as #3, every detections found by VirusTotal scan are generic. Most likely based on a heuristic detection. Heuristics are more prone to false-positive detections.

This [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to [report this](https://github.com/crazy-max/WindowsSpyBlocker/issues/82#issuecomment-337611345) to your Antivirus software vendor.

And since the wrapper `discord-portable.exe` is open source, you can verify that it does not include any malware.

Of course i will try to find dependencies and system calls to avoid heuristic detection like this. I also think that the architecture of the executable (ia32) is also a consequence of the problem encountered. I'll analyze that and let you know.

**Comment by crazy-max** [comment]
@jyrkive, can you try the [latest release](https://github.com/portapps/discord-portable/releases/latest) ? Thx

**Comment by crazy-max** [comment]
I have submit `discord-portable.exe` to Kaspersky for example and here is their response :

> Hello,
> 
> Sorry, it was a false detection. It will be fixed.
> Thank you for your help.
> 
> Sincerely yours,
> Alexander Kolesnikov, Malware Analyst, Kaspersky Lab
> 
> 39A/3 Leningradskoe Shosse, Moscow, 125212, Russia  Tel./Fax: + 7 (495) 797 8700  http://www.kaspersky.com https://securelist.com

**Comment by jyrkive** [comment]
Thanks, it's much better now. :)
